# Generated by Django 6.0.4 on 2026-06-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Siswa',
        ),
    ]
